//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My5032Project_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> RecipientUserID { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string Status { get; set; }
        public byte[] Attachment { get; set; }
    
        public virtual User User { get; set; }
    }
}
