//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My5032Project_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XRayRecord
    {
        public int RecordID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public byte[] XRayImage { get; set; }
        public System.DateTime DateTaken { get; set; }
        public string Description { get; set; }
        public string Diagnosis { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
